name: Trigger workflow
on:
  workflow_dispatch:

jobs:
 LoginTest:
    uses: ./.github/workflows/main.yml
    with:
      env_value: qa_env
 AdminTest:
    needs: LoginTest
    uses: ./.github/workflows/main.yml
    with:
      env_value: uat_env
 StorageTest:
    needs: AdminTest
    uses: ./.github/workflows/main.yml
    with:
      env_value: dev_env
